### PR TITLE
fix: aui-table sticky-column side border disappear, dialog overflow hidden, scroll-shadow extend cdkscroll , table expand row width fix

### LINKED ISSUE #371: aui-table 的 sticky-column 两侧的边框不显示
expect:
image

now:
image

### PR DESCRIPTION
**Pull request by yangxiaolang**
#371

### CODE REVIEW

**Review by JounQin — APPROVED** [review]

**Comment by fengtianze** [comment]
顺便给`auiTableScrollShadow`加个`cdkScrollable`的provider吧

File: src/table/table-scroll.directive.ts [hunk 1]
```diff
@@ -153,8 +169,10 @@ export class TableScrollShadowDirective implements AfterViewInit, OnDestroy {
     classList[condition ? 'add' : 'remove'](className);
   }
 
-  ngOnDestroy() {
+  override ngOnDestroy() {
     this.destroy$$.next();
     this.destroy$$.complete();
+
+    super.ngOnDestroy();
```
Comment (JounQin) [inline src/table/table-scroll.directive.ts:176]: super 的一般放在前面吧，虽然这里没啥影响

**Review by JounQin — CHANGES_REQUESTED** [review]

File: src/table/table-scroll.directive.ts (hunk 1 above)
Comment (yangxiaolang) [reply src/table/table-scroll.directive.ts]: 👌

**Review by JounQin — APPROVED** [review]

**Review by fengtianze — APPROVED** [review]
